language: node_js

node_js: stable

cache:
  directories:
    - node_modules 

install:
  - npm install 
  - npm install -g hexo-cli

script:
  - hexo clean
  - hexo generate

after_script:
  - set -ev
  - export TZ='Asia/Shanghai'
  - git clone https://${GH_REPO} .deploy_git
  - cd .deploy_git
  - git checkout master
  - cd ../
  - mv .deploy_git/.git/ ./public/
  - cd ./public
  - git config user.name "royeo" 
  - git config user.email "ljn6176@163.com" 
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REPO}" master:master

branches:
  only:
    - source

env:
  global:
    - GH_REPO: github.com/royeo/royeo.github.io.git